version: "3.8"
services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/swagger/user.json
    volumes:
      - ./goctl-swagger/user.json:/swagger/user.json
    ports:
      - 17888:8080