// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code  int    `json:"code"`
	Msg   string `json:"msg"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfoRequest struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
