// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Name    string `json:"name"`
	Message string `json:"message"`
}
